version: "3.8"

services:
  acestream-server:
    container_name: acestream-server
    image: ghcr.io/crstian19/docker-acestream-server:main
    restart: always
    ports:
      - "6878:6878"
    volumes:
      - ./acestream.conf:/acestream.conf
