name: Build and Push Docker Image with Kaniko

on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Kaniko builder
      uses: aevea/action-kaniko@master
      with:
        registry: ghcr.io
        password: ${{ secrets.GITHUB_TOKEN }}
        cache: true
        image: ${{ github.event.repository.name }}
        cache_registry: cache
        tag_with_latest: true

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}
