name: Build and Push Docker Image with Kaniko

on:
  push:
    branches: [ main ]
jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo
      uses: actions/checkout@v2

    - name: Set up Kaniko
      uses: GoogleContainerTools/kaniko-action@v1.0.0
      with:
        image: ghcr.io/${{ github.repository }}/docker-acestream-server:latest
        context: . 
        registry: ghcr.io
        dockerfile: Dockerfile  #

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and Push Docker Image
      run: |
        /kaniko/executor --context ${GITHUB_WORKSPACE} --dockerfile ${GITHUB_WORKSPACE}/Dockerfile --destination ghcr.io/${{ github.repository }}:latest
